print('1) Hello, world\n')
print('2) 1 2 3 4 5\n')
print('3) 1\n   2\n   3\n   4\n   5\n')
print('4) *\n   **\n   ***\n   ****\n   *****\n')
a=input()
print('5) Привет,',a)
b=input()
c=input()
d=input()
print('6)',d,'\n  ',c,'\n  ',b)